// <auto-generated />
using LindisBakery.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LindisBakery.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251214142520_Updaty")]
    partial class Updaty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LindisBakery.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Muffins",
                            Description = "Juicy beef patty with fresh lettuce, tomato, and special sauce",
                            ImageUrl = "/images/packet.jpeg",
                            IsAvailable = true,
                            Name = "Blueberry Muffins",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Scones",
                            Description = "Classic pizza with fresh mozzarella, tomatoes, and basil",
                            ImageUrl = "/images/packet.jpeg",
                            IsAvailable = true,
                            Name = "Dumplings",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Dumplings",
                            Description = "Fresh romaine lettuce with Caesar dressing, croutons and parmesan",
                            ImageUrl = "/images/blueberry.jpeg",
                            IsAvailable = true,
                            Name = "Chocolate Muffins",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Cupcakes",
                            Description = "Rich chocolate cake with chocolate ganache",
                            ImageUrl = "/images/blueberry.jpeg",
                            IsAvailable = true,
                            Name = "Vanilla Muffins",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Muffins",
                            Description = "Cold brewed coffee with ice and milk",
                            ImageUrl = "/images/blueberry.jpeg",
                            IsAvailable = true,
                            Name = "Chocolate Mint Muffins",
                            Price = 3.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
